@url = http://localhost:5000
@reservationId = a2f593ea-7981-4254-90fb-dc746112be1a

@parkingSpotId = 00000000-0000-0000-0000-000000000001

@userId = 5cbc290d-a226-40ef-a76e-a298514c31d8

###
GET {{url}}

###
GET {{url}}/users 

###
GET {{url}}/users/{{userId}}

###
POST {{url}}/users
Content-Type: application/json

{ 
    "email": "user1@myspot.io",
    "username": "user1",
    "password": "secret",
    "fullName": "Joe Node",
    "role": "user"
} 

###
GET {{url}}/parking-spots
 
###
POST {{url}}/parking-spots/{{parkingSpotId}}/reservations/vehicle
Content-Type: application/json

{ 
    "capacity": 1,
    "employeeName": "Joe Node",
    "licensePlate": "XYZ123",
    "date": "2022-09-23"    
} 

###
POST {{url}}/parking-spots/reservations/cleaning
Content-Type: application/json

{ 
    "date": "2022-09-23"    
}

###
PUT {{url}}/parking-spots/reservations/{{reservationId}}
Content-Type: application/json

{
    "licensePlate": "XYZ124"
}

###
DELETE  {{url}}/parking-spots/reservations/{{reservationId}}